version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonar
      - store_test_results:
          path: ~/build/reports/jacoco

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud